### ISSUE TITLE
Error wget https://github.com/NekoOs/gsht.sh/releases/download/nightly/gsht

### ISSUE THREAD

**Issue by aacos13** [NekoOs/gsht.sh#5]
![image](https://user-images.githubusercontent.com/87659611/165099178-af007f00-a8ba-40df-8ec5-3ea1073950d5.png)
![image](https://user-images.githubusercontent.com/87659611/165099302-91011fed-66ae-4dcc-b207-b00ebfa6c9ac.png)

**Comment by jgarc58** [comment]
Hello @aacos13, meanwhile this error is happening in our organization's repositories, I released a new version of `josdagaro/tfsuit` `v0.6.4` which is using the latest `NekoOs/gsht.sh` version which is `v0.1.0`.

That should solve the error you're showing us above.
@NekoOs please don't remove old releases regarding multiple projects are using them.

**Comment by NekoOs** [comment]
I'm sorry, I was cleaning the repository and I deleted the tag, I have already restored it; I invite you to try the versions that I will be uploading in these months.

![image](https://user-images.githubusercontent.com/14964692/165342837-87db2a60-1f89-4303-ac3c-ad5360989d4a.png)

For your peace of mind I promise never to remove this tag again.
